backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # 图片保存路径
collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "date", label: "日期", widget: "datetime" }
      - { name: "content", label: "内容", widget: "markdown" }
      - { name: "cover", label: "封面图", widget: "image" }